- name: install apache
  apt:
    name: apache2
    state: present

- name: start apache
  service:
    name: apache2
    state: started

- name: copy index.html
  become: yes
  copy:
    src: files/index.html
    dest: "{{ apache_docs }}"