- name: Exo1 version 1
  hosts: s1
  gather_facts: no # ignore l'étape de collecte d'infos des cibles
  
  tasks:
  - name: install nodejs
    become: yes
    apt:
      name: nodejs
      update_cache: yes
      state: present
  
  - name: git clone repo
    git:
      repo: 'https://gitlab.com/cdufour1/nodeapp.git'
      dest: /home/akka/nodeapp

  - name: run script
    shell: node nodeapp/script.js > output.txt